package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Addhotel generated by hbm2java
 */
public class Addhotel implements java.io.Serializable {

	private Integer hotelid;
	private Registration registration;
	private String hotelname;
	private String hoteladdress;
	private String hotelphoneno;
	private byte[] hotelimg;
	private String hotelemail;
	private String services;
	private String paymentmethod;
	private String hoteltimefrm;
	private String hoteltimeto;
	private String hoteldays;
	private Set nvegmenus = new HashSet(0);
	private Set vegmenus = new HashSet(0);

	public Addhotel() {
	}

	public Addhotel(Registration registration, String hotelname, String hoteladdress, String hotelphoneno,
			byte[] hotelimg, String hotelemail, String services, String paymentmethod, String hoteltimefrm,
			String hoteltimeto, String hoteldays, Set nvegmenus, Set vegmenus) {
		this.registration = registration;
		this.hotelname = hotelname;
		this.hoteladdress = hoteladdress;
		this.hotelphoneno = hotelphoneno;
		this.hotelimg = hotelimg;
		this.hotelemail = hotelemail;
		this.services = services;
		this.paymentmethod = paymentmethod;
		this.hoteltimefrm = hoteltimefrm;
		this.hoteltimeto = hoteltimeto;
		this.hoteldays = hoteldays;
		this.nvegmenus = nvegmenus;
		this.vegmenus = vegmenus;
	}

	public Integer getHotelid() {
		return this.hotelid;
	}

	public void setHotelid(Integer hotelid) {
		this.hotelid = hotelid;
	}

	public Registration getRegistration() {
		return this.registration;
	}

	public void setRegistration(Registration registration) {
		this.registration = registration;
	}

	public String getHotelname() {
		return this.hotelname;
	}

	public void setHotelname(String hotelname) {
		this.hotelname = hotelname;
	}

	public String getHoteladdress() {
		return this.hoteladdress;
	}

	public void setHoteladdress(String hoteladdress) {
		this.hoteladdress = hoteladdress;
	}

	public String getHotelphoneno() {
		return this.hotelphoneno;
	}

	public void setHotelphoneno(String hotelphoneno) {
		this.hotelphoneno = hotelphoneno;
	}

	public byte[] getHotelimg() {
		return this.hotelimg;
	}

	public void setHotelimg(byte[] hotelimg) {
		this.hotelimg = hotelimg;
	}

	public String getHotelemail() {
		return this.hotelemail;
	}

	public void setHotelemail(String hotelemail) {
		this.hotelemail = hotelemail;
	}

	public String getServices() {
		return this.services;
	}

	public void setServices(String services) {
		this.services = services;
	}

	public String getPaymentmethod() {
		return this.paymentmethod;
	}

	public void setPaymentmethod(String paymentmethod) {
		this.paymentmethod = paymentmethod;
	}

	public String getHoteltimefrm() {
		return this.hoteltimefrm;
	}

	public void setHoteltimefrm(String hoteltimefrm) {
		this.hoteltimefrm = hoteltimefrm;
	}

	public String getHoteltimeto() {
		return this.hoteltimeto;
	}

	public void setHoteltimeto(String hoteltimeto) {
		this.hoteltimeto = hoteltimeto;
	}

	public String getHoteldays() {
		return this.hoteldays;
	}

	public void setHoteldays(String hoteldays) {
		this.hoteldays = hoteldays;
	}

	public Set getNvegmenus() {
		return this.nvegmenus;
	}

	public void setNvegmenus(Set nvegmenus) {
		this.nvegmenus = nvegmenus;
	}

	public Set getVegmenus() {
		return this.vegmenus;
	}

	public void setVegmenus(Set vegmenus) {
		this.vegmenus = vegmenus;
	}

}
