package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Addtocart generated by hbm2java
 */
public class Addtocart implements java.io.Serializable {

	private Integer id;
	private String name;
	private String prize;

	public Addtocart() {
	}

	public Addtocart(String name, String prize) {
		this.name = name;
		this.prize = prize;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPrize() {
		return this.prize;
	}

	public void setPrize(String prize) {
		this.prize = prize;
	}

}
