package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Cardpayment generated by hbm2java
 */
public class Cardpayment implements java.io.Serializable {

	private Integer cardid;
	private Integer atmno;
	private Integer cvvno;
	private Date validity;
	private String bankname;

	public Cardpayment() {
	}

	public Cardpayment(Integer atmno, Integer cvvno, Date validity, String bankname) {
		this.atmno = atmno;
		this.cvvno = cvvno;
		this.validity = validity;
		this.bankname = bankname;
	}

	public Integer getCardid() {
		return this.cardid;
	}

	public void setCardid(Integer cardid) {
		this.cardid = cardid;
	}

	public Integer getAtmno() {
		return this.atmno;
	}

	public void setAtmno(Integer atmno) {
		this.atmno = atmno;
	}

	public Integer getCvvno() {
		return this.cvvno;
	}

	public void setCvvno(Integer cvvno) {
		this.cvvno = cvvno;
	}

	public Date getValidity() {
		return this.validity;
	}

	public void setValidity(Date validity) {
		this.validity = validity;
	}

	public String getBankname() {
		return this.bankname;
	}

	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

}
