package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Cod generated by hbm2java
 */
public class Cod implements java.io.Serializable {

	private Integer codid;
	private String address;
	private Integer pincode;

	public Cod() {
	}

	public Cod(String address, Integer pincode) {
		this.address = address;
		this.pincode = pincode;
	}

	public Integer getCodid() {
		return this.codid;
	}

	public void setCodid(Integer codid) {
		this.codid = codid;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getPincode() {
		return this.pincode;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

}
