package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nvegeggmaincourse generated by hbm2java
 */
public class Nvegeggmaincourse implements java.io.Serializable {

	private Integer eggmaincourseid;
	private String eggmenutype;
	private Integer eggprize;
	private Set nvegmenus = new HashSet(0);

	public Nvegeggmaincourse() {
	}

	public Nvegeggmaincourse(String eggmenutype, Integer eggprize, Set nvegmenus) {
		this.eggmenutype = eggmenutype;
		this.eggprize = eggprize;
		this.nvegmenus = nvegmenus;
	}

	public Integer getEggmaincourseid() {
		return this.eggmaincourseid;
	}

	public void setEggmaincourseid(Integer eggmaincourseid) {
		this.eggmaincourseid = eggmaincourseid;
	}

	public String getEggmenutype() {
		return this.eggmenutype;
	}

	public void setEggmenutype(String eggmenutype) {
		this.eggmenutype = eggmenutype;
	}

	public Integer getEggprize() {
		return this.eggprize;
	}

	public void setEggprize(Integer eggprize) {
		this.eggprize = eggprize;
	}

	public Set getNvegmenus() {
		return this.nvegmenus;
	}

	public void setNvegmenus(Set nvegmenus) {
		this.nvegmenus = nvegmenus;
	}

}
