package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nvegbiryanees generated by hbm2java
 */
public class Nvegbiryanees implements java.io.Serializable {

	private Integer biryaneesid;
	private String biryaneemenutype;
	private Integer biryaneeprize;
	private Set nvegmenus = new HashSet(0);

	public Nvegbiryanees() {
	}

	public Nvegbiryanees(String biryaneemenutype, Integer biryaneeprize, Set nvegmenus) {
		this.biryaneemenutype = biryaneemenutype;
		this.biryaneeprize = biryaneeprize;
		this.nvegmenus = nvegmenus;
	}

	public Integer getBiryaneesid() {
		return this.biryaneesid;
	}

	public void setBiryaneesid(Integer biryaneesid) {
		this.biryaneesid = biryaneesid;
	}

	public String getBiryaneemenutype() {
		return this.biryaneemenutype;
	}

	public void setBiryaneemenutype(String biryaneemenutype) {
		this.biryaneemenutype = biryaneemenutype;
	}

	public Integer getBiryaneeprize() {
		return this.biryaneeprize;
	}

	public void setBiryaneeprize(Integer biryaneeprize) {
		this.biryaneeprize = biryaneeprize;
	}

	public Set getNvegmenus() {
		return this.nvegmenus;
	}

	public void setNvegmenus(Set nvegmenus) {
		this.nvegmenus = nvegmenus;
	}

}
