package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nvegchickenmaincourse generated by hbm2java
 */
public class Nvegchickenmaincourse implements java.io.Serializable {

	private Integer chickenmaincourseid;
	private String chickenmenutype;
	private Integer chickenprize;
	private Set nvegmenus = new HashSet(0);

	public Nvegchickenmaincourse() {
	}

	public Nvegchickenmaincourse(String chickenmenutype, Integer chickenprize, Set nvegmenus) {
		this.chickenmenutype = chickenmenutype;
		this.chickenprize = chickenprize;
		this.nvegmenus = nvegmenus;
	}

	public Integer getChickenmaincourseid() {
		return this.chickenmaincourseid;
	}

	public void setChickenmaincourseid(Integer chickenmaincourseid) {
		this.chickenmaincourseid = chickenmaincourseid;
	}

	public String getChickenmenutype() {
		return this.chickenmenutype;
	}

	public void setChickenmenutype(String chickenmenutype) {
		this.chickenmenutype = chickenmenutype;
	}

	public Integer getChickenprize() {
		return this.chickenprize;
	}

	public void setChickenprize(Integer chickenprize) {
		this.chickenprize = chickenprize;
	}

	public Set getNvegmenus() {
		return this.nvegmenus;
	}

	public void setNvegmenus(Set nvegmenus) {
		this.nvegmenus = nvegmenus;
	}

}
