package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Nvegsoupmenu generated by hbm2java
 */
public class Nvegsoupmenu implements java.io.Serializable {

	private Integer nvegsoupmenuid;
	private String nvegsouptype;
	private Integer prize;
	private Integer nvegmenuid;

	public Nvegsoupmenu() {
	}

	public Nvegsoupmenu(String nvegsouptype, Integer prize, Integer nvegmenuid) {
		this.nvegsouptype = nvegsouptype;
		this.prize = prize;
		this.nvegmenuid = nvegmenuid;
	}

	public Integer getNvegsoupmenuid() {
		return this.nvegsoupmenuid;
	}

	public void setNvegsoupmenuid(Integer nvegsoupmenuid) {
		this.nvegsoupmenuid = nvegsoupmenuid;
	}

	public String getNvegsouptype() {
		return this.nvegsouptype;
	}

	public void setNvegsouptype(String nvegsouptype) {
		this.nvegsouptype = nvegsouptype;
	}

	public Integer getPrize() {
		return this.prize;
	}

	public void setPrize(Integer prize) {
		this.prize = prize;
	}

	public Integer getNvegmenuid() {
		return this.nvegmenuid;
	}

	public void setNvegmenuid(Integer nvegmenuid) {
		this.nvegmenuid = nvegmenuid;
	}

}
