package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nvegstarter generated by hbm2java
 */
public class Nvegstarter implements java.io.Serializable {

	private Integer nvegstarterid;
	private String nvegstartermenutype;
	private Integer nstaterprize;
	private Set nvegmenus = new HashSet(0);

	public Nvegstarter() {
	}

	public Nvegstarter(String nvegstartermenutype, Integer nstaterprize, Set nvegmenus) {
		this.nvegstartermenutype = nvegstartermenutype;
		this.nstaterprize = nstaterprize;
		this.nvegmenus = nvegmenus;
	}

	public Integer getNvegstarterid() {
		return this.nvegstarterid;
	}

	public void setNvegstarterid(Integer nvegstarterid) {
		this.nvegstarterid = nvegstarterid;
	}

	public String getNvegstartermenutype() {
		return this.nvegstartermenutype;
	}

	public void setNvegstartermenutype(String nvegstartermenutype) {
		this.nvegstartermenutype = nvegstartermenutype;
	}

	public Integer getNstaterprize() {
		return this.nstaterprize;
	}

	public void setNstaterprize(Integer nstaterprize) {
		this.nstaterprize = nstaterprize;
	}

	public Set getNvegmenus() {
		return this.nvegmenus;
	}

	public void setNvegmenus(Set nvegmenus) {
		this.nvegmenus = nvegmenus;
	}

}
