package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Nvegricemenu generated by hbm2java
 */
public class Nvegricemenu implements java.io.Serializable {

	private Integer nvegricemenuid;
	private String nvegmenutype;
	private Integer prize;
	private Integer nvegmenuid;

	public Nvegricemenu() {
	}

	public Nvegricemenu(String nvegmenutype, Integer prize, Integer nvegmenuid) {
		this.nvegmenutype = nvegmenutype;
		this.prize = prize;
		this.nvegmenuid = nvegmenuid;
	}

	public Integer getNvegricemenuid() {
		return this.nvegricemenuid;
	}

	public void setNvegricemenuid(Integer nvegricemenuid) {
		this.nvegricemenuid = nvegricemenuid;
	}

	public String getNvegmenutype() {
		return this.nvegmenutype;
	}

	public void setNvegmenutype(String nvegmenutype) {
		this.nvegmenutype = nvegmenutype;
	}

	public Integer getPrize() {
		return this.prize;
	}

	public void setPrize(Integer prize) {
		this.prize = prize;
	}

	public Integer getNvegmenuid() {
		return this.nvegmenuid;
	}

	public void setNvegmenuid(Integer nvegmenuid) {
		this.nvegmenuid = nvegmenuid;
	}

}
