package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Nvegmuttonmaincourse generated by hbm2java
 */
public class Nvegmuttonmaincourse implements java.io.Serializable {

	private Integer muttonmaincourseid;
	private String muttonmenutype;
	private Integer muttonprize;
	private Set nvegmenus = new HashSet(0);

	public Nvegmuttonmaincourse() {
	}

	public Nvegmuttonmaincourse(String muttonmenutype, Integer muttonprize, Set nvegmenus) {
		this.muttonmenutype = muttonmenutype;
		this.muttonprize = muttonprize;
		this.nvegmenus = nvegmenus;
	}

	public Integer getMuttonmaincourseid() {
		return this.muttonmaincourseid;
	}

	public void setMuttonmaincourseid(Integer muttonmaincourseid) {
		this.muttonmaincourseid = muttonmaincourseid;
	}

	public String getMuttonmenutype() {
		return this.muttonmenutype;
	}

	public void setMuttonmenutype(String muttonmenutype) {
		this.muttonmenutype = muttonmenutype;
	}

	public Integer getMuttonprize() {
		return this.muttonprize;
	}

	public void setMuttonprize(Integer muttonprize) {
		this.muttonprize = muttonprize;
	}

	public Set getNvegmenus() {
		return this.nvegmenus;
	}

	public void setNvegmenus(Set nvegmenus) {
		this.nvegmenus = nvegmenus;
	}

}
