package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration implements java.io.Serializable {

	private Integer regid;
	private Role role;
	private String firstname;
	private String lastname;
	private String gender;
	private Date bdate;
	private String mobileno;
	private String emailid;
	private String password;
	private String confirmpassword;
	private String address;
	private String areaname;
	private String city;
	private String pincode;
	private Set addhotels = new HashSet(0);

	public Registration() {
	}

	public Registration(Role role, String firstname, String lastname, String gender, Date bdate, String mobileno,
			String emailid, String password, String confirmpassword, String address, String areaname, String city,
			String pincode, Set addhotels) {
		this.role = role;
		this.firstname = firstname;
		this.lastname = lastname;
		this.gender = gender;
		this.bdate = bdate;
		this.mobileno = mobileno;
		this.emailid = emailid;
		this.password = password;
		this.confirmpassword = confirmpassword;
		this.address = address;
		this.areaname = areaname;
		this.city = city;
		this.pincode = pincode;
		this.addhotels = addhotels;
	}

	public Integer getRegid() {
		return this.regid;
	}

	public void setRegid(Integer regid) {
		this.regid = regid;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getBdate() {
		return this.bdate;
	}

	public void setBdate(Date bdate) {
		this.bdate = bdate;
	}

	public String getMobileno() {
		return this.mobileno;
	}

	public void setMobileno(String mobileno) {
		this.mobileno = mobileno;
	}

	public String getEmailid() {
		return this.emailid;
	}

	public void setEmailid(String emailid) {
		this.emailid = emailid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getConfirmpassword() {
		return this.confirmpassword;
	}

	public void setConfirmpassword(String confirmpassword) {
		this.confirmpassword = confirmpassword;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getAreaname() {
		return this.areaname;
	}

	public void setAreaname(String areaname) {
		this.areaname = areaname;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	public Set getAddhotels() {
		return this.addhotels;
	}

	public void setAddhotels(Set addhotels) {
		this.addhotels = addhotels;
	}

}
