package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private Integer roleid;
	private String rolltype;
	private Set registrations = new HashSet(0);

	public Role() {
	}

	public Role(String rolltype, Set registrations) {
		this.rolltype = rolltype;
		this.registrations = registrations;
	}

	public Integer getRoleid() {
		return this.roleid;
	}

	public void setRoleid(Integer roleid) {
		this.roleid = roleid;
	}

	public String getRolltype() {
		return this.rolltype;
	}

	public void setRolltype(String rolltype) {
		this.rolltype = rolltype;
	}

	public Set getRegistrations() {
		return this.registrations;
	}

	public void setRegistrations(Set registrations) {
		this.registrations = registrations;
	}

}
