package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roti generated by hbm2java
 */
public class Roti implements java.io.Serializable {

	private Integer rotiid;
	private String roticategory;
	private Integer rotiprize;
	private Set vegmenus = new HashSet(0);

	public Roti() {
	}

	public Roti(String roticategory, Integer rotiprize, Set vegmenus) {
		this.roticategory = roticategory;
		this.rotiprize = rotiprize;
		this.vegmenus = vegmenus;
	}

	public Integer getRotiid() {
		return this.rotiid;
	}

	public void setRotiid(Integer rotiid) {
		this.rotiid = rotiid;
	}

	public String getRoticategory() {
		return this.roticategory;
	}

	public void setRoticategory(String roticategory) {
		this.roticategory = roticategory;
	}

	public Integer getRotiprize() {
		return this.rotiprize;
	}

	public void setRotiprize(Integer rotiprize) {
		this.rotiprize = rotiprize;
	}

	public Set getVegmenus() {
		return this.vegmenus;
	}

	public void setVegmenus(Set vegmenus) {
		this.vegmenus = vegmenus;
	}

}
