package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vegmenu generated by hbm2java
 */
public class Vegmenu implements java.io.Serializable {

	private Integer vegid;
	private Vegrice vegrice;
	private Addhotel addhotel;
	private Vegsabji vegsabji;
	private Vegstarter vegstarter;
	private Sweets sweets;
	private Roti roti;

	public Vegmenu() {
	}

	public Vegmenu(Vegrice vegrice, Addhotel addhotel, Vegsabji vegsabji, Vegstarter vegstarter, Sweets sweets,
			Roti roti) {
		this.vegrice = vegrice;
		this.addhotel = addhotel;
		this.vegsabji = vegsabji;
		this.vegstarter = vegstarter;
		this.sweets = sweets;
		this.roti = roti;
	}

	public Integer getVegid() {
		return this.vegid;
	}

	public void setVegid(Integer vegid) {
		this.vegid = vegid;
	}

	public Vegrice getVegrice() {
		return this.vegrice;
	}

	public void setVegrice(Vegrice vegrice) {
		this.vegrice = vegrice;
	}

	public Addhotel getAddhotel() {
		return this.addhotel;
	}

	public void setAddhotel(Addhotel addhotel) {
		this.addhotel = addhotel;
	}

	public Vegsabji getVegsabji() {
		return this.vegsabji;
	}

	public void setVegsabji(Vegsabji vegsabji) {
		this.vegsabji = vegsabji;
	}

	public Vegstarter getVegstarter() {
		return this.vegstarter;
	}

	public void setVegstarter(Vegstarter vegstarter) {
		this.vegstarter = vegstarter;
	}

	public Sweets getSweets() {
		return this.sweets;
	}

	public void setSweets(Sweets sweets) {
		this.sweets = sweets;
	}

	public Roti getRoti() {
		return this.roti;
	}

	public void setRoti(Roti roti) {
		this.roti = roti;
	}

}
