package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Vegrice generated by hbm2java
 */
public class Vegrice implements java.io.Serializable {

	private Integer vegriceid;
	private String vegmenutype;
	private Integer riceprize;
	private Set vegmenus = new HashSet(0);

	public Vegrice() {
	}

	public Vegrice(String vegmenutype, Integer riceprize, Set vegmenus) {
		this.vegmenutype = vegmenutype;
		this.riceprize = riceprize;
		this.vegmenus = vegmenus;
	}

	public Integer getVegriceid() {
		return this.vegriceid;
	}

	public void setVegriceid(Integer vegriceid) {
		this.vegriceid = vegriceid;
	}

	public String getVegmenutype() {
		return this.vegmenutype;
	}

	public void setVegmenutype(String vegmenutype) {
		this.vegmenutype = vegmenutype;
	}

	public Integer getRiceprize() {
		return this.riceprize;
	}

	public void setRiceprize(Integer riceprize) {
		this.riceprize = riceprize;
	}

	public Set getVegmenus() {
		return this.vegmenus;
	}

	public void setVegmenus(Set vegmenus) {
		this.vegmenus = vegmenus;
	}

}
