package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vegsoupmenu generated by hbm2java
 */
public class Vegsoupmenu implements java.io.Serializable {

	private Integer vegsoupmenuid;
	private String vegsoupmenutype;
	private Integer prize;
	private Integer vegmenuid;

	public Vegsoupmenu() {
	}

	public Vegsoupmenu(String vegsoupmenutype, Integer prize, Integer vegmenuid) {
		this.vegsoupmenutype = vegsoupmenutype;
		this.prize = prize;
		this.vegmenuid = vegmenuid;
	}

	public Integer getVegsoupmenuid() {
		return this.vegsoupmenuid;
	}

	public void setVegsoupmenuid(Integer vegsoupmenuid) {
		this.vegsoupmenuid = vegsoupmenuid;
	}

	public String getVegsoupmenutype() {
		return this.vegsoupmenutype;
	}

	public void setVegsoupmenutype(String vegsoupmenutype) {
		this.vegsoupmenutype = vegsoupmenutype;
	}

	public Integer getPrize() {
		return this.prize;
	}

	public void setPrize(Integer prize) {
		this.prize = prize;
	}

	public Integer getVegmenuid() {
		return this.vegmenuid;
	}

	public void setVegmenuid(Integer vegmenuid) {
		this.vegmenuid = vegmenuid;
	}

}
