package com.pojo;

// Generated Mar 26, 2018 8:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Vegstarter generated by hbm2java
 */
public class Vegstarter implements java.io.Serializable {

	private Integer vegstatermenuid;
	private String vegstatermenutype;
	private Integer staterprize;
	private Set vegmenus = new HashSet(0);

	public Vegstarter() {
	}

	public Vegstarter(String vegstatermenutype, Integer staterprize, Set vegmenus) {
		this.vegstatermenutype = vegstatermenutype;
		this.staterprize = staterprize;
		this.vegmenus = vegmenus;
	}

	public Integer getVegstatermenuid() {
		return this.vegstatermenuid;
	}

	public void setVegstatermenuid(Integer vegstatermenuid) {
		this.vegstatermenuid = vegstatermenuid;
	}

	public String getVegstatermenutype() {
		return this.vegstatermenutype;
	}

	public void setVegstatermenutype(String vegstatermenutype) {
		this.vegstatermenutype = vegstatermenutype;
	}

	public Integer getStaterprize() {
		return this.staterprize;
	}

	public void setStaterprize(Integer staterprize) {
		this.staterprize = staterprize;
	}

	public Set getVegmenus() {
		return this.vegmenus;
	}

	public void setVegmenus(Set vegmenus) {
		this.vegmenus = vegmenus;
	}

}
